[workspace]

resolver = "2"

members = [
    "crates/relayer",
    "crates/relayer-types",
    "crates/relayer-cli",
    "crates/relayer-rest",
    "crates/telemetry",
    "crates/chain-registry",
    "tools/integration-test",
    "tools/test-framework",
]

exclude = [
    "tools/check-guide",
    "tools/query-events",
]

[profile.release]
overflow-checks = true

[patch.crates-io]
tendermint                       = { git = "https://github.com/astriaorg/tendermint-rs.git", rev = "07e084c4ededd1a24e19030e53041aabe5b1d7a0" }
tendermint-rpc                   = { git = "https://github.com/astriaorg/tendermint-rs.git", rev = "07e084c4ededd1a24e19030e53041aabe5b1d7a0" }
tendermint-proto                 = { git = "https://github.com/astriaorg/tendermint-rs.git", rev = "07e084c4ededd1a24e19030e53041aabe5b1d7a0" }
tendermint-light-client          = { git = "https://github.com/astriaorg/tendermint-rs.git", rev = "07e084c4ededd1a24e19030e53041aabe5b1d7a0" }
tendermint-light-client-verifier = { git = "https://github.com/astriaorg/tendermint-rs.git", rev = "07e084c4ededd1a24e19030e53041aabe5b1d7a0" }
tendermint-light-client-detector = { git = "https://github.com/astriaorg/tendermint-rs.git", rev = "07e084c4ededd1a24e19030e53041aabe5b1d7a0" }
tendermint-testgen               = { git = "https://github.com/astriaorg/tendermint-rs.git", rev = "07e084c4ededd1a24e19030e53041aabe5b1d7a0" }
